# .cnb.yml
$:
  # vscode 事件：专供页面中启动远程开发用
  vscode:
    # 启动 vscode 服务
    - docker:
        # 自定义开发环境
        build:
          # 指定构建镜像的 Dockerfile 文件
          dockerfile: .ide/Dockerfile
      services:
        # 声明使用 vscode 服务
        - vscode
        # 声明在容器中支持 docker 命令
        - docker
      runner:
        cpus: 16
      stages:
        # 环境启动后需要执行的命令
        - name: 安装依赖
          script: echo "环境准备完成"
  tag_push:
    # 上传二进制包到 release 附件
    - docker:
        build: .ide/Dockerfile
      stages:
        - name: 更新日志
          image: cnbcool/changelog
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: 创建发布
          type: git:release
          options:
            title: release
            description: ${LATEST_CHANGE_LOG}
        - name: 构建 amd64 静态 aria2 包
          script: 
            - bash aria2-gnu-linux-build-amd64.sh
        - name: 构建 arm64 静态 aria2 包(交叉编译)
          script: 
            - bash aria2-gnu-linux-cross-build-arm64.sh
        - name: 构建 armhf 静态 aria2 包(交叉编译)
          script: 
            - bash aria2-gnu-linux-cross-build-armhf.sh
        - name: 构建 i386 静态 aria2 包(交叉编译)
          script: 
            - bash aria2-gnu-linux-cross-build-i386.sh
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - "/root/output/*.tar.gz"